application:
  jwt:
    secret: ${JWT_SECRET:MI1IBIjANBgk4qhk3iG9w0BA3QE2F6AAO8CAQ8AM5IIBCgK0CA7QE4A53VzmIVV3ZZWyNm266l82}
    duration-in-minutes: ${JWT_EXPIRATION:30}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:vk_id_backend_intern}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_by.default_null_ordering: last
        format_sql: true
    show_sql: true
    open-in-view: true
    generate-ddl: true